### ISSUE TITLE
🐛 Bug: Columns with type ["null", "array"] can't be typecasted

### ISSUE THREAD

**Issue by tinomerl** [airbytehq/PyAirbyte#101]
# Problem Description

I tested PyAirbyte with the LinkedIn Pages Source. Check and everything works like a charm but when I try to read the data I get the following Error Message in the terminal:

> Could not determine airbyte type from JSON schema: {'type': ['null', 'array'], 'items': {'items': {}}}

It appears multiple times and it seems to only happen when the items property is empty in the selected stream schema. I tried two different streams from the LinkedIn Pages Source independently. `organization_lookup` and `follower_statistics`. When trying to fetch data from the first one the mentioned error occured. The second stream was successful. Looking at their individual schemas lead me to conclusion with the empty items property.

- [organization_lookup schema](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-linkedin-pages/source_linkedin_pages/schemas/organization_lookup.json)
- [follower_statistics schema](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-linkedin-pages/source_linkedin_pages/schemas/follower_statistics.json)

# Example Code

```python
import airbyte as ab

source: ab.Source = ab.get_source("source-linkedin-pages")

config = {
    "org_id": "redacted",
    "credentials": {
        "auth_method": "oAuth2.0",
        "client_id": "redacted",
        "client_secret": "redacted",
        "refresh_token": "redacted"
    }
}

source.set_config(config)
source.check()

source.select_streams("follower_statistics")
# source.select_streams("organization_lookup")
read_results = source.read()

```

**Comment by aaronsteers** [comment]
@tinomerl - Thanks for reporting this! 

I believe this may be resolved in the (WIP) PR:

- #67 

In the meanwhile, you may be able to work around this issue for your use case by applying `Source.get_records(stream_name)` for the problematic streams.

The "real" fix is of course to solve the type conversion failure, which #67 should hopefully address.

**Comment by tinomerl** [comment]
Hey @aaronsteers,

Thanks for the response and the info. I'll watch out for this PR and test it afterwards again. Also thanks for the workaround. Currently we are evaluating PyAirbyte as an opportunity for smaller serverless deployments, so we are not relying on it yet. :)

**Comment by aaronsteers** [comment]
@tinomerl - We've just merged #67, and will release soon. If you have time to test by installing PyAirbyte from the `main` branch, this would be much appreciated. Otherwise, we will likely do a few more tests on our side and release tomorrow morning (US time) if all is looking good.

**Comment by tinomerl** [comment]
@aaronsteers - thanks for the info. I just retested it, but the bug is still there, with the same error Message. It's exactly as described above. One Stream works, but the other doesn't.

**Comment by aaronsteers** [comment]
@tinomerl - is this result installing with the GitHub link? 

You'd need to install via GitHub to get the unreleased version from `main` branch. Would be something like this:

`pip install git+https://www.github.com/airbytehq/PyAirbyte.git`

**Comment by tinomerl** [comment]
hey @aaronsteers,

thanks for the info and the fix. Just wanted to let you know, that i just retested it with the your changes and it now works like a charm.

> One thing is still confusing to me - which is that the error you describe is generally printed as a warning and would be non-fatal - although it does make sense that you could still experience a subsequent additional failure if data is later loaded into an incorrect column type.

I think the reason why i didn't get any records for this specific stream could have been, that the stream contains only one record, when fetched correctly?

The Log btw is now completly free of errors and warnings.

<img width="358" alt="image" src="https://github.com/airbytehq/PyAirbyte/assets/35485536/cc9f4b0b-7240-424f-a4fc-790da5d34fde">

Thanks again for the fix! 🚀

**Comment by aaronsteers** [comment]
@tinomerl - thanks for the confirmation! Very helpful and I'm glad we were able to resolve the issue. 🎉
